service: basic-serverless-lambda-github

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1


functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}


