service: basic-serverless-lambda-github

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: false
    binaryMediaTypes:
      - "*/*"
  vpc:
    securityGroupIds:
      - sg-0f163352ed8a5ce7c
    subnetIds:
      - subnet-0441d8c4785f6123d
      - subnet-0e33ff58ee97867c4
      - subnet-0ba83aff67f52f18d

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}


